import test from 'node:test'
import assert from 'node:assert/strict'
import { spawnSync } from 'node:child_process'
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const SCRIPT = join(ROOT, 'plugins/macro-loop/scripts/stage.mjs')
const { stageOf, noteState } = await import(pathToFileURL(SCRIPT).href)

const signals = (over = {}) => ({
  closed: false,
  states: [],
  priority: true,
  spec: false,
  branchAhead: false,
  pr: null,
  note: { addressedTo: null, resumable: false },
  ...over,
})
const pr = (over = {}) => ({ state: 'open', head: 'h2', verdicts: 0, result: null, sha: null, ...over })
const pick = (over) => {
  const { stage, gate } = stageOf(signals(over))
  return [stage, gate]
}

test('rows: each row of the table gives its stage and gate', () => {
  const rows = [
    [{ closed: true }, ['done', false]],
    [{ states: ['wontfix'] }, ['done', false]],
    [{ states: ['ready', 'needsInfo'] }, ['stop', true]],
    [{ pr: pr({ state: 'merged' }) }, ['done', false]],
    [{ pr: pr({ verdicts: 3, result: 'NEEDS-FIX', sha: 'h2' }) }, ['stop', true]],
    [{ pr: pr({ verdicts: 1, result: 'PASS', sha: 'h2' }) }, ['merge', true]],
    [{ pr: pr({ verdicts: 1, result: 'NEEDS-FIX', sha: 'h2' }) }, ['implement', false]],
    [{ pr: pr() }, ['verify', false]],
    [{ branchAhead: true }, ['open-pr', false]],
    [{ states: ['needsInfo'], note: { addressedTo: 'requester', resumable: true } }, ['resumable', true]],
    [{ states: ['needsDecision'] }, ['grilling', true]],
    [{ states: ['needsInfo'], note: { addressedTo: 'user', resumable: false } }, ['grilling', true]],
    [{ states: ['needsInfo'], note: { addressedTo: 'requester', resumable: false } }, ['wait', true]],
    [{ priority: false }, ['triage', false]],
    [{ states: ['ready'] }, ['grilling', true]],
    [{ states: ['ready'], spec: true }, ['implement', false]],
    [{}, ['stop', true]],
  ]
  for (const [over, expected] of rows) assert.deepEqual(pick(over), expected, JSON.stringify(over))
})

test('proxy: a needs-info note for the user gives wait; needs-decision and a non-proxy Issue stay grilling', () => {
  const toUser = { addressedTo: 'user', resumable: false }
  assert.deepEqual(pick({ states: ['needsInfo'], note: toUser, proxy: true }), ['wait', true])
  assert.deepEqual(pick({ states: ['needsInfo'], note: toUser, proxy: false }), ['grilling', true])
  assert.deepEqual(pick({ states: ['needsDecision'], note: toUser, proxy: true }), ['grilling', true])
})

test('precedence: the first matching row wins', () => {
  assert.equal(stageOf(signals({ states: ['ready', 'needsDecision'], pr: pr({ state: 'merged' }) })).stage, 'stop')
  assert.equal(stageOf(signals({ closed: true, pr: pr() })).stage, 'done')
  assert.equal(stageOf(signals({ pr: pr({ state: 'merged' }), branchAhead: true, states: ['needsInfo'] })).stage, 'done')
  assert.equal(stageOf(signals({ pr: pr(), branchAhead: true })).stage, 'verify')
  assert.equal(stageOf(signals({ branchAhead: true, states: ['needsDecision'], priority: false })).stage, 'open-pr')
})

test('verdicts: the cap holds after a push; a verdict for an older head sends the PR to verify', () => {
  assert.equal(stageOf(signals({ pr: pr({ verdicts: 3, result: 'NEEDS-FIX', sha: 'old' }) })).stage, 'stop')
  assert.equal(stageOf(signals({ pr: pr({ verdicts: 2, result: 'NEEDS-FIX', sha: 'h2' }) })).stage, 'implement')
  assert.equal(stageOf(signals({ pr: pr({ verdicts: 2, result: 'NEEDS-FIX', sha: 'old' }) })).stage, 'verify')
  assert.equal(stageOf(signals({ pr: pr({ verdicts: 1, result: 'PASS', sha: 'old' }) })).stage, 'verify')
})

test('verdicts: a verdict with no SHA counts as judging the current head', () => {
  assert.equal(stageOf(signals({ pr: pr({ verdicts: 1, result: 'PASS', sha: null }) })).stage, 'merge')
})

test('no row fits: stop, and why names the signals', () => {
  const r = stageOf(signals({ spec: false, priority: true }))
  assert.equal(r.stage, 'stop')
  assert.match(r.why, /priority=true spec=false branch=false pr=none/)
})

const NOTE = '> *This was generated by AI during triage.*\n\n**What we still need from you (@carol):**\n- q'
const c = (login, body) => ({ user: { login }, body })

test('note: resumable only for a trusted, non-AI comment after the newest note', () => {
  const trusted = ['carol']
  assert.equal(noteState([c('carol', NOTE), c('carol', 'It is (b)')], trusted).resumable, true)
  assert.equal(noteState([c('carol', NOTE)], trusted).resumable, false)
  assert.equal(noteState([c('carol', 'It is (b)'), c('carol', NOTE)], trusted).resumable, false)
  assert.equal(noteState([c('carol', NOTE), c('mallory', 'It is (b)')], trusted).resumable, false)
  assert.equal(noteState([c('carol', NOTE), c('carol', '> *This was generated by AI during triage.*\nmore')], trusted).resumable, false)
  assert.equal(noteState([c('carol', NOTE), c('carol', '<!-- macro-loop:verify round=1 -->\nPASS')], trusted).resumable, false)
  assert.equal(noteState([c('mallory', NOTE)], trusted).resumable, false)
})

test('note: addressed to a trusted login is the user; anyone else is the requester', () => {
  assert.equal(noteState([c('carol', NOTE)], ['carol']).addressedTo, 'user')
  assert.equal(noteState([c('dave', NOTE)], ['dave']).addressedTo, 'requester')
  assert.equal(noteState([], ['carol']).addressedTo, null)
})

// A stand-in for `gh`, as in trust.test.mjs: answers each call from a table keyed by its
// arguments, logs every call, and fails on a call the table does not have.
const STUB = `#!/usr/bin/env node
const fs = require('fs')
const key = process.argv.slice(2).join(' ')
fs.appendFileSync(process.env.GH_LOG, key + '\\n')
const r = JSON.parse(fs.readFileSync(process.env.GH_STUB, 'utf8'))[key]
if (!r) { process.stderr.write('stub: unexpected call: gh ' + key + '\\n'); process.exit(99) }
if (r.stdout !== undefined) process.stdout.write(typeof r.stdout === 'string' ? r.stdout : JSON.stringify(r.stdout))
if (r.stderr) process.stderr.write(r.stderr)
process.exit(r.code ?? 0)
`

const git = (cwd, ...args) => spawnSync('git', ['-C', cwd, '-c', 'user.name=t', '-c', 'user.email=t@t', ...args], { encoding: 'utf8' })

// A checkout with origin/main, and, with `branch`, a branch ahead of it.
function runStage(responses, { branch } = {}) {
  const tmp = mkdtempSync(join(tmpdir(), 'stage-'))
  mkdirSync(join(tmp, 'bin'))
  writeFileSync(join(tmp, 'bin', 'gh'), STUB)
  chmodSync(join(tmp, 'bin', 'gh'), 0o755)
  writeFileSync(join(tmp, 'stub.json'), JSON.stringify(responses))
  const cwd = join(tmp, 'checkout')
  mkdirSync(cwd)
  git(cwd, 'init', '-q')
  git(cwd, 'commit', '-q', '--allow-empty', '-m', 'base')
  git(cwd, 'update-ref', 'refs/remotes/origin/main', 'HEAD')
  if (branch) {
    git(cwd, 'switch', '-q', '-c', branch)
    git(cwd, 'commit', '-q', '--allow-empty', '-m', 'work')
  }
  const env = { PATH: `${join(tmp, 'bin')}:${dirname(process.execPath)}:/usr/bin:/bin`, GH_STUB: join(tmp, 'stub.json'), GH_LOG: join(tmp, 'calls.log') }
  writeFileSync(env.GH_LOG, '')
  const r = spawnSync(process.execPath, [SCRIPT, '--issue', '77'], { cwd, env, encoding: 'utf8' })
  return { ...r, calls: readFileSync(env.GH_LOG, 'utf8').split('\n').filter(Boolean), out: r.status === 0 ? JSON.parse(r.stdout) : null }
}

const repo = { stdout: { owner: { login: 'JuHyeonni', type: 'User' }, default_branch: 'main' } }
const contents = { stdout: { content: Buffer.from(JSON.stringify({ trusted: [] })).toString('base64'), encoding: 'base64' } }
const spec = { id: 1, user: { login: 'JuHyeonni' }, body: '<!-- macro-loop:spec -->' }
const ISSUE_COMMENTS = 'api --paginate --slurp repos/{owner}/{repo}/issues/77/comments'
const PULLS = 'api --paginate --slurp repos/{owner}/{repo}/pulls?state=all&per_page=100'
const base = (over = {}) => ({
  'api user': { stdout: { login: 'Carol' } },
  'api repos/{owner}/{repo}': repo,
  'api repos/{owner}/{repo}/contents/.github/macro-loop.json': contents,
  'api repos/{owner}/{repo}/issues/77': { stdout: { state: 'open', labels: [{ name: 'P1' }, { name: 'ready-for-agent' }] } },
  [ISSUE_COMMENTS]: { stdout: [[spec]] },
  [PULLS]: { stdout: [[]] },
  ...over,
})
test('run: an Issue with a spec and no branch or PR gives implement, and makes no write call', () => {
  const r = runStage(base())
  assert.equal(r.status, 0, r.stderr)
  assert.deepEqual([r.out.stage, r.out.gate], ['implement', false])
  assert.equal(r.calls.some((call) => /(^| )-X /.test(call)), false)
  assert.equal(r.calls.filter((call) => call === ISSUE_COMMENTS).length, 1)
})

test('run: the proxy label comes from the config, so a renamed label gives wait and source:proxy does not', () => {
  const labels = (name) => ({ stdout: { state: 'open', labels: [{ name: 'P1' }, { name: 'needs-info' }, { name }] } })
  const note = { id: 3, user: { login: 'Carol' }, body: '> *This was generated by AI during triage.*\nWhat we still need from you (@Carol)' }
  const renamed = { stdout: { content: Buffer.from(JSON.stringify({ trusted: [], labels: { source: { proxy: 'via-proxy' } } })).toString('base64'), encoding: 'base64' } }
  const run = (config, label) => runStage(base({
    'api repos/{owner}/{repo}/contents/.github/macro-loop.json': config,
    'api repos/{owner}/{repo}/issues/77': labels(label),
    [ISSUE_COMMENTS]: { stdout: [[spec, note]] },
  }))
  assert.equal(run(renamed, 'via-proxy').out.stage, 'wait')
  assert.equal(run(renamed, 'source:proxy').out.stage, 'grilling')
  assert.equal(run(contents, 'source:proxy').out.stage, 'wait')
})

test('run: a local branch ahead of the default branch gives open-pr', () => {
  const r = runStage(base(), { branch: '77-stage-script' })
  assert.equal(r.status, 0, r.stderr)
  assert.equal(r.out.stage, 'open-pr')
})

test('run: an open PR with a PASS for its head gives merge, taking the PR from the list without reading it again', () => {
  const r = runStage(base({
    [PULLS]: { stdout: [[{ number: 5, state: 'open', merged_at: null, body: 'Closes #77', user: { login: 'carol' }, head: { sha: 'abc1234' }, base: { ref: 'main' } }]] },
    'api --paginate --slurp repos/{owner}/{repo}/issues/5/comments': { stdout: [[{ id: 2, user: { login: 'carol' }, body: '<!-- macro-loop:verify round=1 sha=abc1234 -->\n## Verify: PASS (round 1 of 3)' }]] },
  }))
  assert.equal(r.status, 0, r.stderr)
  assert.deepEqual([r.out.stage, r.out.gate], ['merge', true])
  assert.equal(r.calls.includes('api repos/{owner}/{repo}/pulls/5'), false)
})

test('run: a failing gh call prints nothing on stdout, the error on stderr, and exits non-zero', () => {
  const r = runStage(base({ 'api repos/{owner}/{repo}/issues/77': { stderr: 'gh: Not Found (HTTP 404)\n', code: 1 } }))
  assert.notEqual(r.status, 0)
  assert.equal(r.stdout, '')
  assert.match(r.stderr, /stage\.mjs: .*404/)
})
