#!/usr/bin/env node
// Decides an Issue's next stage from GitHub state, the same way every time (#77): which
// skill comes next, and whether a person is needed to choose or act.
//
//   node stage.mjs --issue <n>
//
// Run it in the repo's checkout, like trust.mjs, which it runs for trust, the spec and
// the PR's verdict. It reads only. It prints one JSON line `{stage, why, gate}`. On any
// failure it prints nothing and exits non-zero with the error.
import { spawnSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { parseArgs } from 'node:util'

const TRUST = fileURLToPath(new URL('./trust.mjs', import.meta.url))
const TRIAGE_NOTE = '> *This was generated by AI during triage.*'
const AI_PREFIXES = ['> *This was generated by AI', '<!-- macro-loop:']
const ADDRESSEE = /What we still need from you \(@([A-Za-z0-9-]+)/
const CLOSES = /^\s*closes\s+#(\d+)\b/im

const row = (stage, why, gate = false) => ({ stage, why, gate })
const lower = (login) => String(login ?? '').toLowerCase()

// A verdict without a recorded SHA counts as current, so a PR verified before the SHA was
// written is not verified again.
function stageOfPr(pr) {
  const current = pr.sha === null || pr.sha === pr.head
  if (pr.verdicts >= 3 && pr.result === 'NEEDS-FIX') return row('stop', `${pr.verdicts} verdicts and the newest is NEEDS-FIX`, true)
  if (pr.verdicts > 0 && current && pr.result === 'PASS') return row('merge', 'the verdict for the current head is PASS', true)
  if (pr.verdicts > 0 && current && pr.result === 'NEEDS-FIX') return row('implement', 'the verdict for the current head is NEEDS-FIX')
  return row('verify', 'no verdict for the current head')
}

// signals: { closed, states: ['ready'|'needsInfo'|'needsDecision'|'wontfix'], priority, spec,
// branchAhead, pr: null | { state: 'open'|'merged', head, verdicts, result, sha }, note: { addressedTo, resumable } }
// The first matching row wins.
export function stageOf(s) {
  const has = (state) => s.states.includes(state)
  if (s.closed || has('wontfix')) return row('done', 'the Issue is closed or wontfix')
  if (s.states.length > 1) return row('stop', `more than one state label: ${s.states.join(', ')}`, true)
  if (s.pr?.state === 'merged') return row('done', 'the PR is merged')
  if (s.pr) return stageOfPr(s.pr)
  if (s.branchAhead) return row('open-pr', 'the branch has commits and no PR')
  if ((has('needsInfo') || has('needsDecision')) && s.note.resumable) return row('resumable', 'a person answered after the note; confirm with next', true)
  if (has('needsDecision')) return row('grilling', 'a decision is needed', true)
  if (has('needsInfo')) {
    return s.note.addressedTo === 'user'
      ? row('grilling', 'the note asks the user', true)
      : row('wait', 'waiting for the requester; offer a draft of the questions', true)
  }
  if (!s.priority) return row('triage', 'no priority label')
  if (has('ready') && !s.spec) return row('grilling', 'ready-for-agent without a spec: grilling, then spec', true)
  if (s.spec) return row('implement', 'a spec and no branch')
  return row('stop', `no rule fits: states=[${s.states}] priority=${s.priority} spec=${s.spec} branch=${s.branchAhead} pr=none`, true)
}

// The newest triage note a trusted login wrote, who it asks, and whether a trusted login
// has commented after it with something that is not AI-written.
export function noteState(comments, trusted) {
  const body = (c) => String(c.body ?? '')
  const isTrusted = (c) => trusted.includes(lower(c.user?.login))
  const at = comments.findLastIndex((c) => isTrusted(c) && body(c).startsWith(TRIAGE_NOTE))
  if (at < 0) return { addressedTo: null, resumable: false }
  const who = ADDRESSEE.exec(body(comments[at]))?.[1]
  return {
    addressedTo: !who ? null : trusted.includes(lower(who)) ? 'user' : 'requester',
    resumable: comments.slice(at + 1).some((c) => isTrusted(c) && !AI_PREFIXES.some((p) => body(c).startsWith(p))),
  }
}

function run(cmd, args) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', maxBuffer: 64 << 20 })
  if (r.error) throw r.error
  if (r.status !== 0) throw new Error(`${cmd} ${args.join(' ')} failed: ${(r.stderr || r.stdout).trim()}`)
  return r.stdout
}

const api = (args) => JSON.parse(run('gh', ['api', ...args]))

// The PR is the one whose body closes the Issue; an open one wins over a merged one.
// A PR closed without merging is ignored. The list is newest first.
function findPr(n) {
  const prs = api(['--paginate', '--slurp', 'repos/{owner}/{repo}/pulls?state=all&per_page=100']).flat()
  const mine = prs.filter((p) => Number(CLOSES.exec(p.body ?? '')?.[1]) === n && (p.state === 'open' || p.merged_at))
  return mine.find((p) => p.state === 'open') ?? mine[0] ?? null
}

// A local branch named <n>-* that is ahead of the default branch: the one `implement` makes.
function branchAhead(n, base) {
  const branches = run('git', ['for-each-ref', '--format=%(refname:short)', `refs/heads/${n}-*`]).split('\n').filter(Boolean)
  return branches.some((b) => Number(run('git', ['rev-list', '--count', `origin/${base}..${b}`])) > 0)
}

function decide(argv) {
  const { values } = parseArgs({ args: argv, options: { issue: { type: 'string' } } })
  if (!/^\d+$/.test(values.issue ?? '')) throw new Error('--issue takes a number')
  const n = Number(values.issue)

  const issue = api([`repos/{owner}/{repo}/issues/${n}`])
  const comments = api(['--paginate', '--slurp', `repos/{owner}/{repo}/issues/${n}/comments`]).flat()
  const pr = findPr(n)
  const trust = JSON.parse(run(process.execPath, [TRUST, '--issue', String(n), ...(pr ? ['--pr', String(pr.number)] : [])]))
  const base = api(['repos/{owner}/{repo}']).default_branch

  const names = new Set(issue.labels.map((l) => l.name))
  const { state, priority } = trust.config.labels
  return stageOf({
    closed: issue.state === 'closed',
    states: Object.entries(state).filter(([, label]) => names.has(label)).map(([key]) => key),
    priority: Object.values(priority).some((label) => names.has(label)),
    spec: trust.issue.spec !== null,
    branchAhead: branchAhead(n, base),
    pr: pr && {
      state: pr.state === 'open' ? 'open' : 'merged',
      head: trust.pr.head,
      verdicts: trust.pr.round - 1,
      result: trust.pr.lastVerdictResult,
      sha: trust.pr.lastVerdictSha,
    },
    note: noteState(comments, trust.trusted),
  })
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  try {
    process.stdout.write(`${JSON.stringify(decide(process.argv.slice(2)))}\n`)
  } catch (e) {
    process.stderr.write(`stage.mjs: ${e.message}\n`)
    process.exitCode = 1
  }
}
