import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { dirname, resolve, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const START = '<!-- PLUGINS:START'
const END = '<!-- PLUGINS:END -->'

// every plugin folder that has a manifest, sorted by folder name
export function readManifests(pluginsDir) {
  return readdirSync(pluginsDir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()
    .map((dir) => {
      const manifestPath = join(pluginsDir, dir, '.claude-plugin', 'plugin.json')
      if (!existsSync(manifestPath)) return null
      const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
      return {
        dir,
        name: manifest.name,
        description: manifest.description ?? '',
        requirements: manifest.requirements ?? '—',
        version: manifest.version ?? '',
      }
    })
    .filter(Boolean)
}

// only plugins the marketplace lists; an unlisted folder stays out
export function listedPlugins(marketplace, manifests) {
  const names = new Set((marketplace.plugins ?? []).map((p) => p.name))
  return manifests.filter((m) => names.has(m.name))
}

// refresh listed entries (keeping extra fields); never adds an entry
export function syncMarketplace(marketplace, listed) {
  const previous = new Map((marketplace.plugins ?? []).map((p) => [p.name, p]))
  return {
    ...marketplace,
    plugins: listed.map((p) => ({
      ...previous.get(p.name),
      name: p.name,
      source: `./plugins/${p.dir}`,
      description: p.description,
    })),
  }
}

const cell = (s) => String(s).replace(/\|/g, '\\|')
const firstSentence = (s) => {
  const str = String(s).trim()
  const m = str.match(/^.*?[.。](\s|$)/s)
  return m ? m[0].trim() : str
}

export function readmeBlock(marketplaceName, listed) {
  const header = '| Plugin | Description | Requirements | Version | Install |\n|---|---|---|---|---|'
  const rows = listed
    .map(
      (p) =>
        `| [${p.name}](plugins/${p.dir}/) | ${cell(firstSentence(p.description))} | ${cell(p.requirements)} | ${p.version || '—'} | \`/plugin install ${p.name}@${marketplaceName}\` |`,
    )
    .join('\n')
  return `${START} — generated by scripts/gen-readme.mjs. Do not edit by hand. -->\n${header}\n${rows}\n${END}`
}

export function replaceBlock(readme, block) {
  const startIdx = readme.indexOf(START)
  const endIdx = readme.indexOf(END)
  if (startIdx === -1 || endIdx === -1) throw new Error('README markers not found')
  return readme.slice(0, startIdx) + block + readme.slice(endIdx + END.length)
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
  const marketplacePath = join(root, '.claude-plugin', 'marketplace.json')
  const readmePath = join(root, 'README.md')
  const marketplace = JSON.parse(readFileSync(marketplacePath, 'utf8'))
  const listed = listedPlugins(marketplace, readManifests(join(root, 'plugins')))
  if (listed.length === 0) throw new Error('No plugins found under plugins/*')
  writeFileSync(marketplacePath, JSON.stringify(syncMarketplace(marketplace, listed), null, 2) + '\n')
  const readme = readFileSync(readmePath, 'utf8')
  writeFileSync(readmePath, replaceBlock(readme, readmeBlock(marketplace.name, listed)))
  console.log(`Synced ${listed.length} plugin(s): ${listed.map((p) => p.name).join(', ')}`)
}
