import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs'
import { dirname, resolve, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const marketplacePath = join(root, '.claude-plugin', 'marketplace.json')
const readmePath = join(root, 'README.md')
const pluginsDir = join(root, 'plugins')

const marketplace = JSON.parse(readFileSync(marketplacePath, 'utf8'))
const marketplaceName = marketplace.name

const plugins = readdirSync(pluginsDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort()
  .map((dir) => {
    const manifestPath = join(pluginsDir, dir, '.claude-plugin', 'plugin.json')
    if (!existsSync(manifestPath)) return null
    const manifest = JSON.parse(readFileSync(manifestPath, 'utf8'))
    return {
      dir,
      name: manifest.name,
      description: manifest.description ?? '',
      requirements: manifest.requirements ?? '—',
      version: manifest.version ?? '',
    }
  })
  .filter(Boolean)

if (plugins.length === 0) throw new Error('No plugins found under plugins/*')

// 1) sync marketplace.json plugins[] (preserve any extra per-entry fields)
const previous = new Map((marketplace.plugins ?? []).map((p) => [p.name, p]))
marketplace.plugins = plugins.map((p) => ({
  ...previous.get(p.name),
  name: p.name,
  source: `./plugins/${p.dir}`,
  description: p.description,
}))
writeFileSync(marketplacePath, JSON.stringify(marketplace, null, 2) + '\n')

// 2) regenerate the README plugin index between markers
const START = '<!-- PLUGINS:START'
const END = '<!-- PLUGINS:END -->'
const cell = (s) => String(s).replace(/\|/g, '\\|')
const firstSentence = (s) => {
  const str = String(s).trim()
  const m = str.match(/^.*?[.。](\s|$)/s)
  return m ? m[0].trim() : str
}
const header = '| Plugin | Description | Requirements | Version | Install |\n|---|---|---|---|---|'
const rows = plugins
  .map(
    (p) =>
      `| [${p.name}](plugins/${p.dir}/) | ${cell(firstSentence(p.description))} | ${cell(p.requirements)} | ${p.version || '—'} | \`/plugin install ${p.name}@${marketplaceName}\` |`,
  )
  .join('\n')
const block = `${START} — generated by scripts/gen-readme.mjs. Do not edit by hand. -->\n${header}\n${rows}\n${END}`

const readme = readFileSync(readmePath, 'utf8')
const startIdx = readme.indexOf(START)
const endIdx = readme.indexOf(END)
if (startIdx === -1 || endIdx === -1) throw new Error('README markers not found')
writeFileSync(readmePath, readme.slice(0, startIdx) + block + readme.slice(endIdx + END.length))

console.log(`Synced ${plugins.length} plugin(s): ${plugins.map((p) => p.name).join(', ')}`)
